// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTjY0tizN1VTU01E8JDB61nj8oXIN31xw',
    appId: '1:364195574726:web:7774f0f1647569cc02b8c7',
    messagingSenderId: '364195574726',
    projectId: 'fooddeliveryapp-67717',
    authDomain: 'fooddeliveryapp-67717.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-67717.firebasestorage.app',
    measurementId: 'G-EF7Y09D6YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2C_Q2h3XcFRckfRpV8WuyCvNzTXZJ98',
    appId: '1:364195574726:android:f4a53df996cbfe5b02b8c7',
    messagingSenderId: '364195574726',
    projectId: 'fooddeliveryapp-67717',
    storageBucket: 'fooddeliveryapp-67717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCehzGX58BJhgQGY-aUkHMy5JPWBktqjoo',
    appId: '1:364195574726:ios:01be56dee121a71f02b8c7',
    messagingSenderId: '364195574726',
    projectId: 'fooddeliveryapp-67717',
    storageBucket: 'fooddeliveryapp-67717.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCehzGX58BJhgQGY-aUkHMy5JPWBktqjoo',
    appId: '1:364195574726:ios:01be56dee121a71f02b8c7',
    messagingSenderId: '364195574726',
    projectId: 'fooddeliveryapp-67717',
    storageBucket: 'fooddeliveryapp-67717.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTjY0tizN1VTU01E8JDB61nj8oXIN31xw',
    appId: '1:364195574726:web:f219803c173113a502b8c7',
    messagingSenderId: '364195574726',
    projectId: 'fooddeliveryapp-67717',
    authDomain: 'fooddeliveryapp-67717.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-67717.firebasestorage.app',
    measurementId: 'G-G1LYNHFNB1',
  );
}
